# Generated by Django 4.2 on 2023-04-10 18:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Coords',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.FloatField(verbose_name='Широта')),
                ('longitude', models.FloatField(verbose_name='Долгота')),
                ('height', models.IntegerField(verbose_name='Высота над уровнем моря')),
            ],
        ),
        migrations.CreateModel(
            name='Level',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('winter', models.CharField(choices=[('н/к', 'некатегорийный'), ('1А', 'новый'), ('2А', 'модератор взял в работу'), ('2А', 'модерация прошла успешно'), ('3А', 'модерация прошла, информация не принята'), ('3Б', 'модерация прошла, информация не принята')], max_length=15, null=True, verbose_name='Зима')),
                ('summer', models.CharField(choices=[('н/к', 'некатегорийный'), ('1А', 'новый'), ('2А', 'модератор взял в работу'), ('2А', 'модерация прошла успешно'), ('3А', 'модерация прошла, информация не принята'), ('3Б', 'модерация прошла, информация не принята')], max_length=15, null=True, verbose_name='Лето')),
                ('autumn', models.CharField(choices=[('н/к', 'некатегорийный'), ('1А', 'новый'), ('2А', 'модератор взял в работу'), ('2А', 'модерация прошла успешно'), ('3А', 'модерация прошла, информация не принята'), ('3Б', 'модерация прошла, информация не принята')], max_length=15, null=True, verbose_name='Осень')),
                ('spring', models.CharField(choices=[('н/к', 'некатегорийный'), ('1А', 'новый'), ('2А', 'модератор взял в работу'), ('2А', 'модерация прошла успешно'), ('3А', 'модерация прошла, информация не принята'), ('3Б', 'модерация прошла, информация не принята')], max_length=15, null=True, verbose_name='Весна')),
            ],
        ),
        migrations.CreateModel(
            name='PerevalAdded',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('beauty_title', models.CharField(max_length=255, verbose_name='')),
                ('title', models.CharField(max_length=255, verbose_name='Название')),
                ('other_titles', models.CharField(max_length=255, verbose_name='')),
                ('connect', models.CharField(max_length=255, null=True)),
                ('add_time', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('new', 'новый'), ('pending', 'модератор взял в работу'), ('accepted', 'модерация прошла успешно'), ('rejected', 'модерация прошла, информация не принята')], default='new', max_length=10)),
                ('coords', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pereval.coords')),
                ('level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pereval.level', verbose_name='Категория трудности')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
