# Generated by Django 4.2 on 2023-04-12 10:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pereval', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='coords',
            options={'verbose_name': 'Координаты', 'verbose_name_plural': 'Координаты'},
        ),
        migrations.AlterModelOptions(
            name='images',
            options={'verbose_name': 'Изображения', 'verbose_name_plural': 'Изображения'},
        ),
        migrations.AlterModelOptions(
            name='level',
            options={'verbose_name': 'Уровень сложности', 'verbose_name_plural': 'Уровень сложности'},
        ),
        migrations.AlterModelOptions(
            name='perevaladded',
            options={'verbose_name': 'Перевал', 'verbose_name_plural': 'Перевал'},
        ),
        migrations.AlterModelOptions(
            name='perevaladdedimages',
            options={'verbose_name': 'Перевал-Изображение', 'verbose_name_plural': 'Перевал-Изображение'},
        ),
        migrations.AlterModelOptions(
            name='users',
            options={'verbose_name': 'Пользователи', 'verbose_name_plural': 'Пользователи'},
        ),
        migrations.AlterField(
            model_name='perevaladded',
            name='connect',
            field=models.CharField(blank=True, max_length=255, verbose_name='Что соединяет'),
        ),
        migrations.AlterField(
            model_name='perevaladded',
            name='coords',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pereval.coords', verbose_name='Координаты'),
        ),
        migrations.AlterField(
            model_name='perevaladded',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pereval.users', verbose_name='Ползователь'),
        ),
    ]
